name: country_pickers
description: Countries, codes, flags and several way of picking them at your service...one widget away...
version: 1.3.0
author: Figen Güngör <figengungor1@gmail.com>
homepage: https://github.com/figengungor/country_pickers

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/